---
[f5]
localhost ansible_connection=local

[staging]
23.100.85.61 ansible_user=azureuser
23.101.125.34 ansible_user=azureuser

[production]
104.43.134.23 ansible_user=azureuser
104.43.130.62 ansible_user=azureuser
104.43.139.37 ansible_user=azureuser # exemplo adicionar novo membro ao pool 

[staging:vars]
site_port="80"
partitionname="Common" #Particao onde o pool esta configurado
floating_bigip="104.43.244.96" #IP do FloatingIP entre os BIG-IPs do cluster
serverport="8443"
userbigip=admin
passuser="{{ ANSIBLE_F5_PASS }}"
poolname="pool_demo_php_staging" #Nome do Pool de servidores balanceados

[production:vars]
site_port="80"
partitionname="Common" #Particao onde o pool esta configurado
floating_bigip="104.43.244.96" #IP do FloatingIP entre os BIG-IPs do cluster
serverport="8443"
userbigip=admin
passuser="{{ ANSIBLE_F5_PASS }}"
poolname="pool_demo_php_production" #Nome do Pool de servidores balanceados

[f5:vars]
floating_bigip="104.43.244.96" #IP do FloatingIP entre os BIG-IPs do cluster
serverport="8443"
userbigip=admin
passuser="{{ ANSIBLE_F5_PASS }}"

